#!/usr/bin/env python3
"""Pull the brand mark across from the app repo, so the site cannot drift.

The mark is authored once, in the app repo (`docs/brand/gen_mark.py`), because
the launcher icon is the copy that matters — it is the one people see on a
phone. Everything here is downstream of that: the favicon, the two raster
icons, the social card, and the React component the header and footer draw.

The React component is *generated*, not hand-kept: the mark is 72 short arcs
whose opacities step along the tail, and a human copying that by hand copies it
wrong. Editing `Logo.tsx` directly is therefore pointless — the next sync
overwrites it. Change `gen_mark.py` in the app repo instead and run this.

Run: python3 scripts/brand/sync-mark.py && python3 scripts/brand/gen-assets.py
"""
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
APP = os.path.join(os.path.dirname(REPO), "IELTSAPP", "docs", "brand")

FAVICON = os.path.join(REPO, "client", "public", "favicon.svg")
COMPONENT = os.path.join(REPO, "client", "src", "components", "brand", "Logo.tsx")

# Source in the app repo -> copy here. The rounded tile and the white mark are
# what gen-assets.py rasterises; the SVG is what the browser and the component
# use.
COPIES = (
    (os.path.join(APP, "svg", "icon-primary.svg"), FAVICON),
    (os.path.join(APP, "png", "play-store", "speakband-icon-rounded-1024.png"),
     os.path.join(HERE, "icon-rounded.png")),
    (os.path.join(APP, "png", "speakband-mark-white-1024.png"),
     os.path.join(HERE, "mark-white.png")),
)

# React wants camelCase where SVG spells an attribute with a hyphen.
ATTRS = (
    ("stroke-width", "strokeWidth"), ("stroke-linecap", "strokeLinecap"),
    ("stroke-linejoin", "strokeLinejoin"), ("stop-color", "stopColor"),
    ("stop-opacity", "stopOpacity"), ("fill-rule", "fillRule"),
    ("clip-rule", "clipRule"),
)

HEADER = '''/**
 * The Speakband mark: a ring with a voice inside it.
 *
 * GENERATED by scripts/brand/sync-mark.py from the app repo's own icon — do not
 * edit the paths by hand, they are 72 arcs with stepped opacities and the next
 * sync overwrites them. Drawn in SVG rather than shipped as a PNG so it stays
 * crisp at every size, and identical to the launcher icon rather than merely
 * similar to it: the tile's gradient and corner radius are part of the drawing,
 * so the header shows exactly what sits on the user's home screen.
 */
import { useId } from "react";

export function LogoMark({ className = "" }: { className?: string }) {
  // The gradient's id has to be unique per instance: the header and the footer
  // both draw the mark, and two elements sharing an id is two chances to
  // resolve the wrong one.
  const tile = useId();
  return (
    <svg
      viewBox="0 0 108 108"
      className={className}
      aria-hidden="true"
      focusable="false"
    >
'''

FOOTER = '''
    </svg>
  );
}

export function Wordmark({ className = "" }: { className?: string }) {
  return (
    <span className={`inline-flex items-center gap-2.5 ${className}`}>
      <LogoMark className="h-9 w-9" />
      <span
        className="text-[1.0625rem] font-bold tracking-tight"
        style={{ fontFamily: "var(--font-display)" }}
      >
        Speakband
      </span>
    </span>
  );
}
'''


def component_from(svg: str) -> str:
    body = svg.split(">", 1)[1].rsplit("</svg>", 1)[0].strip()
    for hyphenated, camel in ATTRS:
        body = body.replace(hyphenated + "=", camel + "=")
    body = (body.replace('id="tile"', "id={tile}")
                .replace('"url(#tile)"', "{`url(#${tile})`}"))
    body = "\n".join(("      " + line) if line.strip() else line
                     for line in body.splitlines())
    return HEADER + body + FOOTER


def main() -> None:
    for src, dst in COPIES:
        shutil.copyfile(src, dst)
        print("copied:", os.path.relpath(dst, REPO))
    with open(FAVICON) as f:
        svg = f.read()
    with open(COMPONENT, "w") as f:
        f.write(component_from(svg))
    print("wrote:", os.path.relpath(COMPONENT, REPO))


if __name__ == "__main__":
    main()
